name: EntitySuppressor
main: com.fishrock123.entitysuppressor.ESPlugin
version: 3.0 (1Q0)
author: Fishrock123
website: http://dev.bukkit.org/server-mods/entitysuppressor/
dev-url: http://dev.bukkit.org/server-mods/entitysuppressor/
description: >
    EntitySuppressor: Limit Mobs, Reduce Lag!
softdepend:
- Multiverse-Core
- Multiworld
- WormholeXTremeWorlds
- AnimalRights
commands:
    es:
        usage: 
            /es count <world / all>
            
            /es remove <monsters / animals / squid / bats / npcs / all> <world / all>
permissions:
  esuppressor.*:
    description: Gives access to all EntitySuppressor commands
    children:
      esuppressor.reload: true
      esuppressor.remove: true
  esuppressor.remove:
    description: Allows you to remove loaded entities.
    default: op
  esuppressor.reload:
    description: Allows you to reload EntitySuppressor.
    default: op