name: EntitySuppressor
main: Fishrock123.EntitySuppressor.EntitySuppressor
version: 2.1.2 (1N9)
dev-url: http://dev.bukkit.org/server-mods/entitysuppressor/
description: >
    EntitySuppressor: Take unnecessary stress off your server!
commands:
    es:
        description:
        usage: 
            /es count <world / all>
            
            /es remove <monsters / animals / squid / all> <world / all>