name: EntitySuppressor
main: Fishrock123.EntitySuppressor.EntitySuppressor
version: 1.2 (1F7)
description: >
    EntitySuppressor: Take unnecessary stress off your server!
commands:
    es:
        description:
        usage: 
            /es count - Returns a count of all Living Entities in the current world.
            /es count all - Returns a count of all Living Entities in all worlds.

permissions:
    esuppressor.count:
        description: Allows /es count (all).
        default: op
        