name: EntitySuppressor
main: Fishrock123.EntitySuppressor.EntitySuppressor
version: 1.4 (1I5)
website: http://dev.bukkit.org/server-mods/entitysuppressor/
description: >
    EntitySuppressor: Take unnecessary stress off your server!
commands:
    es:
        description:
        usage: 
            /es count - Returns a count of all Living Entities in the current world.
            /es count all - Returns a count of all Living Entities in all worlds.
permissions:
    esuppressor.count:
        description: Allows /es count (all / world).
        default: op   
    esuppressor.remove:
        description: Allows /es remove (all / world).
        default: op 
    esuppressor.print:
        description: Allows /es print.
        default: op 